Task-5/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("weatherapp/", include("weatherApp.urls")),
    path('admin/', admin.site.urls),
]

Task-5/weatherApp/urls.py
from django.urls import path
from . import views

app_name = "weatherApp"

urlpatterns = [
	path("", views.index, name="index"),
	path("getFive", views.getFive, name="getFive"),
	path("getSingle", views.getSingle, name="getSingle"),
	path("getFromDB", views.getFromDB, name="getFromDB"),
]

Task-5/weatherApp/models.py
from django.db import models

# Create your models here.
class CityData(models.Model):
    name = models.CharField(max_length=60)
    country = models.CharField(max_length=60)
    humidity = models.IntegerField()
    temp = models.FloatField()
    weather_desc = models.CharField(max_length=100)
    clouds = models.CharField(max_length=100)
    clouds_percent = models.IntegerField()
    # Used to order and delete the oldest
    pub_date = models.DateTimeField("date published")

    def __str__(self):
    	return self.name

    class Meta:
       ordering = ['-pub_date']

Task-5/weatherApp/views.py
from django.shortcuts import render
from django.http import JsonResponse
from . import make_requests
from . import write_to_DB
from weatherApp.models import CityData
from django.core import serializers

import json

# Create your views here.
def index(request):
	return render(request, template_name="weatherApp/index.html") 

def getFive(request):
	amount = int(json.load(request))
	requester = make_requests.MakeRequests()

	# write to DB
	cities = requester.collect_cities(amount)
	write_to_DB.write(cities[0], amount)

	json_data = json.dumps(cities)
# Sub-optimal but running out of time
	return JsonResponse(json_data, safe=False)

def getSingle(request):
	name = json.load(request)
	requester = make_requests.MakeRequests()

	# write to DB
	city = requester.get_by_name(name)
# Quick fix
	if city == "Error finding city, or invalid API response.":
		err = json.loads('{"err" : "Error finding city, or invalid API response."}')
		return JsonResponse(json.dumps(err), safe=False)

	write_to_DB.write(city)

	json_data = json.dumps(city)

# Sub-optimal but running out of time
	return JsonResponse(json_data, safe=False)

def getFromDB(request):
	json_data = json.loads(serializers.serialize('json', CityData.objects.all()))
	return JsonResponse(json_data, safe=False)

Task-5/weatherApp/templates/weatherApp/footer.html
 {% load static %}
   <script src="{% static 'weatherApp/main.js' %}"></script>
   <script src="{% static 'weatherApp/access_db.js' %}"></script>
    <!-- Used to get X-CSRF Cookie -->
    <script src=" https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js "></script>
  </body>
</html>

Task-5/weatherApp/templates/weatherApp/header.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weatherApp/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Task 5</title>
  </head>
     <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
          <a href="{% url 'weatherApp:index' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
            <span class="fs-4">Task 5 - Django Web app with DB</span>
          </a>

          <ul class="nav nav-pills">
            <li class="nav-item"><a href="https://github.com/ValKozz/Python-Tasks/tree/main/Task-5" class="nav-link">GitHub</a></li>
          </ul>
        </header>
    <!-- Jumbotron from Bootstrap's website -->
    <div class="my-5">
  <div class="p-5 text-center bg-body-tertiary">
    <div class="container py-5">
      <h1 class="text-body-emphasis">Task 5 - Django based Weather App</h1>
      <p class="col-lg-8 mx-auto lead">
        This is my simple rendition of Task 5, using the Bootsrap templates and examples. 
      </p>
    </div>
  </div>
</div>

Task-5/weatherApp/templates/weatherApp/history.html
<div class="history-container">
<h3> Last 10 searches: </h3>
  <button class="btn btn-outline-primary" type="button" id="RefreshDB">Refresh.</button>
  <div class="history-stats">
      <h4>Average temperature: <a id="avg-temp-history"></a></h4>
      <h4>Codest city in searches: <a id="coldest-history"></a></h4>
  </div>
	<div class="history-cards-wrapper">
        <div id="his-card-container">
           <div class="card">
             <div class="card-body">No data found.</div>
          </div>  
        </div>
    </div>
</div>

Task-5/weatherApp/templates/weatherApp/index.html
{% include "weatherApp/header.html" %}
{% block index %}
{% csrf_token %}
<div class="content_container"> 
  <div class="left half">
    <label fclass="form-label">Number of random cities to collect data on:</label>
      <input type="range" class="form-range" min="1" max="10" step="1" id="bSlider" value=5>
        <div class="container">
          <label>Amount: 
                <label id="sliderValue"></label>
          </label>
          <button class="btn btn-outline-primary" id="getFive">Get!</button>
          <div class="input-group mb-3 text-box">
            <input type="text" class="form-control" placeholder="City name" aria-label="City" aria-describedby="button-addon2" id="cityField">
            <button class="btn btn-outline-secondary" type="button" id="getNamed">Get by name!</button>
          </div>
        </div>
  </div>
  <div class="right half" id="card_container">
    <div class="card">
      <div class="card-body">This will be updated.</div>
     </div>
   </div>
</div>
{% endblock %}
{% include 'weatherApp/history.html' %}

{% include 'weatherApp/footer.html' %}